export const FETCH_MOVIES = 'FETCH_MOVIES';
export const MOVIE_LOADING = 'MOVIE_LOADING';
export const FETCH_DESCRIPTION_MOVIES = 'FETCH_DESCRIPTION_MOVIES';
export const FETCH_SIMILAR_MOVIES = 'FETCH_SIMILAR_MOVIES';
export const DESCRIPTION_LOADING = 'DESCRIPTION_LOADING';
